<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.github.swamx</groupId>
  <artifactId>lemonade-a2a-interop-java</artifactId>
  <version>0.0.0</version>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <a2a.version>1.4.0.Final</a2a.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.a2aproject.sdk</groupId>
      <artifactId>a2a-java-sdk-client</artifactId>
      <version>${a2a.version}</version>
    </dependency>
    <dependency>
      <groupId>org.a2aproject.sdk</groupId>
      <artifactId>a2a-java-sdk-client-transport-jsonrpc</artifactId>
      <version>${a2a.version}</version>
    </dependency>
    <dependency>
      <groupId>org.a2aproject.sdk</groupId>
      <artifactId>a2a-java-sdk-client-transport-rest</artifactId>
      <version>${a2a.version}</version>
    </dependency>
  </dependencies>
</project>
